version: '3.8'

services:
  # ===================
  # MYSQL DATABASE
  # ===================
  mysql:
    image: mysql:8.0
    container_name: shelfit-mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: shelfit_main
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - shelfit-net

  # ===================
  # CONFIG SERVER
  # ===================
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - shelfit-net

  # ===================
  # EUREKA SERVER
  # ===================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    networks:
      - shelfit-net

  # ===================
  # API GATEWAY
  # ===================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - shelfit-net

  # ===================
  # BOOK SERVICE
  # ===================
  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
      - mysql
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shelfit_bookdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - shelfit-net

  # ===================
  # USER SERVICE
  # ===================
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server
      - mysql
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shelfit_userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - shelfit-net

  # ===================
  # ORDER SERVICE
  # ===================
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
      - mysql
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shelfit_orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - shelfit-net

  # ===================
  # INVENTORY SERVICE
  # ===================
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server
      - mysql
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shelfit_inventorydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - shelfit-net

# ===================
# NETWORKS & VOLUMES
# ===================
networks:
  shelfit-net:
    driver: bridge

volumes:
  mysql_data:
