apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose-microservices.yml convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose-microservices.yml convert --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
          image: kapsk/shelfit-config-server:latest
          name: config-server
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
