apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose-microservices.yml convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose-microservices.yml convert --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888/
          image: kapsk/shelfit-eureka-server
          name: eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
