apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose-microservices.yml convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose-microservices.yml convert --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888/
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/shelfit_userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: kapsk/shelfit-user-service
          name: user-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
